import { signal } from '@angular/core';
import type { CartItem } from './eco-store-cart.store';

export const mockEcoStoreCartStore = {
  entities: signal([] as CartItem[]),
  itemsCount: signal(0),
  subtotal: signal(100),
  tax: signal(21),
  total: signal(121),
  isEmpty: signal(true),
  itemsDictionary: signal({} as Record<string, CartItem>),
  items: signal([] as CartItem[]),
  itemsGroupedByCategory: signal({} as Record<string, CartItem[] | undefined>),
  shipping: signal(0),
  address: signal(null),
  day: signal(null),
  time: signal(null),
  method: signal(null),
  noDayAndTime: signal(false),
  status: signal('ACTIVE' as const),
  expiredAt: signal(null),
  orderCycle: signal(null),
  notes: signal(null),
  remoteCartId: signal(null),
  isSyncing: signal(false),
  addToCart: jest.fn(),
  removeFromCart: jest.fn(),
  clearCart: jest.fn(),
  updateLogistics: jest.fn(),
  getItemCount: jest.fn(),
};
