/// <reference path="../pb_data/types.d.ts" />
migrate(
  app => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1579384326',
          max: 0,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'bool2618758466',
          name: 'isAvailable',
          presentable: false,
          required: false,
          system: false,
          type: 'bool',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text73334810',
          max: 0,
          min: 0,
          name: 'normalizedName',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number1261852256',
          max: null,
          min: null,
          name: 'stock',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3740358174',
          max: 0,
          min: 0,
          name: 'origin',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text2462348188',
          max: 0,
          min: 0,
          name: 'provider',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number3402113753',
          max: null,
          min: null,
          name: 'price',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number4221019651',
          max: null,
          min: null,
          name: 'iva',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number773110036',
          max: null,
          min: null,
          name: 'priceWithIva',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3411954233',
          hidden: false,
          id: 'relation2620853105',
          maxSelect: 1,
          minSelect: 0,
          name: 'categoryId',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'file3760176746',
          maxSelect: 10,
          maxSize: 5242880,
          mimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
          name: 'images',
          presentable: false,
          protected: true,
          required: false,
          system: false,
          thumbs: ['100x100'],
          type: 'file',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text2528667032',
          max: 0,
          min: 0,
          name: 'categoryName',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number946921979',
          max: null,
          min: null,
          name: 'unitBase',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'select1947879603',
          maxSelect: 1,
          name: 'unitType',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: [
            'unitWithFixedWeight',
            'unit',
            'weight',
            'unitWithFixedVolume',
            'unitWithVariableWeight',
          ],
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_4092854851',
      indexes: [],
      listRule: null,
      name: 'products',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  app => {
    const collection = app.findCollectionByNameOrId('pbc_4092854851');

    return app.delete(collection);
  }
);
