/* eslint-disable */
/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types apps/eco-store/worker-configuration.d.ts -c apps/eco-store/wrangler.jsonc` (hash: 6615a7b35f1378cfaf151acf75ffcf08)
declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
    POCKETBASE_DEV_URL: string;
    POCKETBASE_DEV_ADMIN_EMAIL: string;
    POCKETBASE_DEV_ADMIN_PASSWORD: string;
    POCKETBASE_STAGING_URL: string;
    POCKETBASE_STAGING_ADMIN_EMAIL: string;
    POCKETBASE_STAGING_ADMIN_PASSWORD: string;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'POCKETBASE_DEV_URL'
      | 'POCKETBASE_DEV_ADMIN_EMAIL'
      | 'POCKETBASE_DEV_ADMIN_PASSWORD'
      | 'POCKETBASE_STAGING_URL'
      | 'POCKETBASE_STAGING_ADMIN_EMAIL'
      | 'POCKETBASE_STAGING_ADMIN_PASSWORD'
    >
  > {}
}
