name: Deploy Staging

on:
  workflow_run:
    workflows: [CI, pa11y nasa-images]
    types: [completed]
    branches:
      - 'develop'

env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: staging
          base_href: ''
          deploy_branch: nasa-images-staging-page
          angular_dist_build_folder: dist/apps/nasa-images
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
