name: Deploy Develop to GitHub Pages

on:
  workflow_run:
    workflows: [CI]
    branches: ['develop']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn nasa-images:build:github
      - name: Create 404
        run: cp dist/apps/nasa-images/index.html dist/apps/nasa-images/404.html
      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: staging
          base_href: ''
          angular_dist_build_folder: dist/apps/nasa-images
          deploy_branch: nasa-images-staging-page
