name: Deploy Staging

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "TOKEN => ${{ github.token }}"
          echo "Workflow run => ${{ github.event.workflow_run}}"
          echo "Workflow run conclusion => ${{ github.event.workflow_run.conclusion}}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: staging
          base_href: ''
          deploy_branch: nasa-images-staging-page
          angular_dist_build_folder: dist/apps/nasa-images
