name: Deploy Develop to GitHub Pages

on:
  workflow_run:
    workflows: [CI]
    branches: ['develop']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn nx build nasa-images --prod
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/nasa-images
          publish_branch: nasa-images-staging-page
          cname: nasa-images-staging.plastikaweb.com
          commit_message: 'Deploy staging nasa-images to GitHub Pages'
          enable_jekyll: false
