name: Deploy Staging

on:
  workflow_run:
    workflows: [CI]
    branches: ['develop']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: staging
          base_href: /nasa-images/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/apps/nasa-images
