name: Plastikspace ci

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on:
  push:
    branches:
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Start Nx Cloud agents for distributed task execution
      - name: Start Nx Cloud CI Run
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --network-timeout 1000000

      - uses: nrwl/nx-set-shas@v4

      # Run linting in parallel
      - name: Lint
        run: yarn nx affected --target=lint --parallel=true --maxParallel=3 --exclude=llecoop-firebase

      # Run tests in parallel
      - name: Test
        run: yarn nx affected --target=test --parallel=true --maxParallel=3 --exclude=llecoop-firebase

      # Run e2e tests in parallel using Nx Cloud agents
      - name: E2E Tests
        run: yarn nx affected --target=e2e-ci --parallel=true --maxParallel=3

      # Stop Nx Cloud agents (this will happen automatically, but explicit is better)
      - name: Stop Nx Cloud agents
        if: always()
        run: npx nx-cloud stop-all-agents
