name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  develop:
    name: nx-cloud
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      number-of-agents: 3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record yarn markdownlint
        yarn nx-cloud record yarn nx format:check
      parallel-commands-on-agents: |
        npx nx affected -t lint,test,build --parallel=2

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
