name: CI
on:
  push:
    branches:
      - develop

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
      - run: yarn install --immutable --network-timeout 1000000

      - uses: nrwl/nx-set-shas@v4

      # Format check
      - run: npx nx-cloud record -- nx format:check --all

      # Run affected tasks excluding llecoop-firebase
      - name: Run Affected Tasks
        run: |
          npx nx affected --target=lint --exclude=llecoop-firebase --parallel=3
          npx nx affected --target=test --exclude=llecoop-firebase --parallel=3
          npx nx affected --target=build --exclude=llecoop-firebase --parallel=3
