name: Deploy Llecoop to hosting

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up firebase
        run: |
          echo "export const firebaseConfig = {" > apps/llecoop/firebase.ts
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> apps/llecoop/firebase.ts
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> apps/llecoop/firebase.ts
          echo "  databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}'," >> apps/llecoop/firebase.ts
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> apps/llecoop/firebase.ts
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> apps/llecoop/firebase.ts
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> apps/llecoop/firebase.ts
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> apps/llecoop/firebase.ts
          echo "};" >> apps/llecoop/firebase.ts

      - name: Install dependencies
        run: |
          yarn install --immutable --network-timeout 1000000
          yarn nx build llecoop --prod --base-href /botiga.llevat.org/

      - name: Set up FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.LLECOOP_FTP_SERVER }}
          username: ${{ secrets.LLECOOP_FTP_USERNAME }}
          password: ${{ secrets.LLECOOP_FTP_PASSWORD }}
          local-dir: ./dist/apps/llecoop/browser/
          server-dir: /
