name: Nasa Images deploy development

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - develop

env:
  NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
  on-success:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npx nx build nasa-images --configuration=development

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/nasa-images
          publish_branch: nasa-images-staging-page

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
