name: PR

on:
  pull_request:
    branches:
      - develop

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install:local

      - name: Format
        run: yarn format:write

      - name: Markdown lint
        run: yarn markdownlint

      - name: Lint
        run: nx affected --target=lint --base=origin/develop --parallel --max-parallel=3 --verbose

      - name: test
        run: nx affected --target=test --base=origin/develop --parallel --max-parallel=3 --verbose
